{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "ab6fac79_a2a038e2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000103
      },
      "writtenOn": "2021-11-08T11:26:29Z",
      "side": 1,
      "message": "We haven\u0027t been able to test fully yet, but on first examination looks good. ",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "21e022d2_36f5bd32",
        "filename": "dmaapadapter/adapter/code/consumer.py",
        "patchSetId": 3
      },
      "lineNbr": 62,
      "author": {
        "id": 1000128
      },
      "writtenOn": "2021-11-10T09:52:14Z",
      "side": 1,
      "message": "dubug -\u003e debug\n\nThis gives the following error:\nDEBUG - Failed to get event information due to unexpected reason! \u0027RootLogger\u0027 object has no attribute \u0027dubug\u0027\n\nI fixed this bug and tried again. Now, I see this error:\nDEBUG - Error reading message : KafkaError{code\u003dUNKNOWN_TOPIC_OR_PART,val\u003d3,str\u003d\"Subscribed topic not available: unauthenticated.SEC_FAULT_OUTPUT: Broker: Unknown topic or partition\"}\n\nI am wondering how would you create a new topic?\nDoes the topic need to be created directly in Kafka, and this dmaap adapter would just read the messages from different topics?\n\nAs a sidenote, even though the above calls fail, the dmaap adapter still returns 200 which also seems to be a bug:\nINFO - 172.22.0.1 - - [10/Nov/2021 09:41:01] \"GET /dmaapapi/v1/events/unauthenticated.SEC_FAULT_OUTPUT/testGroup/testId HTTP/1.1\" 200",
      "revId": "adf450663e6d2956cea62be7429f518a29230752",
      "serverId": "84e4e190-e623-4c37-9eda-58b1937c1b53"
    }
  ]
}